# Frontend build process
FROM node:21
WORKDIR /app
#separate copy for package.json ensures caching
COPY ./package.json .
COPY ./package-lock.json .
RUN npm install

COPY . ./
RUN npm run build

EXPOSE 8080
CMD [ "npm", "run", "dev" ]