# Development compose file
# When ready to deploy make sure to set a permanent volume

version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${dbUser}"
      POSTGRES_PASSWORD: "${dbPassword}"
      POSTGRES_NAME: "${dbName}"

  web:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      POSTGRES_USER: "${dbUser}"
      POSTGRES_PASSWORD: "${dbPassword}"
      POSTGRES_NAME: "${dbName}"
      POSTGRES_PORT: "5432"
    develop:
      watch:
        - action: rebuild
          path: ./backend
        - action: rebuild
          path: ./frontend
