# Development compose file
# When ready to deploy make sure to set a permanent volume

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      # Should we be using docker secrets for these one?
      # For now set the password using .env file
      POSTGRES_PASSWORD: "${dbPassword}"
  web:
    build: .
    ports:
      - "9090:9090"
    develop:
      watch:
        - action: rebuild
          path: ./backend
        - action: rebuild
          path: ./frontend
