export function Contacts() {

    return (
        <div className="contactsContainer">
            <div>
                <h1>Contacts</h1>
            </div>
            <div className="scrollableContacts">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vestibulum nibh ex, vel mattis augue ultrices sit amet. Nullam mollis ipsum ac lacus lacinia rhoncus. Sed ut vulputate mi, vitae dictum turpis. Vestibulum eros purus, porta ac viverra vitae, pulvinar et libero. Sed dapibus malesuada ligula, eget laoreet ante hendrerit at. Suspendisse potenti. Curabitur mollis orci magna, ac ultricies neque pharetra ut. Proin efficitur, eros vitae interdum iaculis, arcu orci faucibus turpis, sit amet imperdiet eros nisi vitae purus. Etiam ultricies urna vitae orci sodales semper. Aenean rhoncus convallis faucibus. Quisque nisi sapien, dictum ut fringilla vel, faucibus a nisl.
                Aliquam a sagittis mauris. Vestibulum accumsan sollicitudin diam eu cursus. Aenean urna neque, vestibulum eu tincidunt vitae, ornare vitae urna. Quisque blandit ac nibh vel cursus. Sed eget eleifend magna. Sed euismod eros nec diam cursus, eu iaculis nisi tristique. Vivamus eros nulla, ullamcorper commodo vulputate at, mattis a orci. Curabitur neque orci, lobortis vitae elit sit amet, vestibulum viverra mi. Proin venenatis felis vel euismod consequat. Nullam id dui sit amet nunc sollicitudin aliquam id pharetra leo.
                Praesent cursus mauris nec sollicitudin consequat. Mauris ullamcorper hendrerit tincidunt. Praesent nisl lacus, ullamcorper ut sagittis at, fermentum nec tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ante urna, ultricies et ullamcorper a, vestibulum ac dolor. Nunc rhoncus dignissim massa, et commodo risus viverra sed. Nunc et erat nec felis faucibus pellentesque quis id eros. Aenean enim enim, tempor ac est at, maximus vulputate mauris. Fusce purus tellus, sodales non risus eu, dignissim gravida elit. Sed bibendum purus eu lorem vulputate, quis porta felis facilisis. Cras tellus justo, porta eget feugiat sed, vehicula sed massa. Ut vitae mi gravida, feugiat erat sed, porttitor lectus.
                Praesent accumsan lacus ac lectus rhoncus egestas. Nullam ac lectus ligula. Pellentesque in lorem sit amet leo tempus viverra. Vivamus condimentum semper leo, at cursus risus congue nec. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi porttitor, massa id sodales sollicitudin, tellus dolor vehicula ipsum, ut ultricies justo mauris vel ex. Vestibulum tempor, quam eget eleifend vulputate, felis dolor tincidunt sapien, id pellentesque arcu neque vitae lectus. Etiam lacinia sapien vel sem tincidunt, nec aliquam ligula convallis. Proin at tincidunt nibh. Nunc nec est at justo fermentum vehicula. Fusce lobortis aliquam neque id posuere. Sed erat nisl, facilisis ut magna eu, porta mattis felis. Quisque eu finibus metus.
                Morbi nec efficitur elit. In augue dolor, gravida et laoreet ac, lobortis a lectus. Duis fermentum vestibulum neque id rutrum. Etiam id ex nec mauris malesuada accumsan nec at libero. Aenean bibendum aliquam neque quis auctor. Phasellus placerat at lacus quis pretium. Suspendisse turpis urna, bibendum at vulputate nec, pulvinar at nunc. Etiam accumsan et sem ac laoreet. Nam gravida nulla sed sapien ullamcorper, at molestie lacus elementum. Morbi eu lorem dui. Vestibulum eget lorem eget leo tincidunt vulputate. Praesent pulvinar elit sed nibh rutrum laoreet. Donec id efficitur turpis. Donec sed orci vitae massa interdum egestas id vel diam.
            </div>
        </div>
    );
}