export function Contacts() {

    return (
        <div className="contactsContainer">
            <div>
                <h1 style={{borderBottom:'1px solid #333'}}>Contacts</h1>
            </div>
            <div className="scrollableContacts">
                {/* Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ultricies iaculis nibh quis volutpat. Sed a blandit leo, vel fringilla ex. In facilisis nisl erat, ac eleifend odio volutpat nec. Integer ut hendrerit eros. In sit amet sollicitudin felis, id pellentesque odio. Vivamus ultricies velit in magna varius sagittis. Donec ac tortor at nisi ornare accumsan sit amet in sem. Fusce lectus odio, vulputate ut accumsan ac, rutrum non neque. Phasellus facilisis facilisis vestibulum. Quisque ipsum eros, posuere sit amet mi vitae, consectetur suscipit quam. Nullam a mauris erat. Quisque ut quam feugiat, volutpat tellus eu, suscipit leo.
                Nunc cursus metus vitae metus luctus tempus. Aliquam ultricies felis ut tellus gravida lacinia. Nunc eu purus nunc. Nulla placerat aliquam scelerisque. Suspendisse id ex interdum, pellentesque erat at, semper tellus. Vestibulum luctus ligula purus, eu sollicitudin sapien fermentum a. Maecenas sit amet ornare nisi, non finibus dui. Integer fermentum, lorem a posuere blandit, odio massa gravida quam, a eleifend tellus lorem vel diam. Maecenas finibus nec orci vel dictum. Cras pulvinar sapien id magna venenatis pellentesque. Nunc a ligula pharetra, efficitur est eget, sodales orci. Nam feugiat accumsan nunc et interdum. Nunc venenatis urna a neque posuere, ac aliquam quam fermentum. Morbi dictum dignissim leo et porttitor.
                Proin aliquet, lorem vitae auctor euismod, enim est gravida sem, vitae malesuada nisi nisi quis mauris. Suspendisse non libero eleifend, laoreet leo hendrerit, euismod nisl. Nunc porta tortor ex. Mauris at odio bibendum, elementum mauris viverra, finibus enim. Vivamus in tincidunt metus, in faucibus arcu. Curabitur id auctor dolor. Etiam congue arcu vitae posuere tempus.
                Praesent non finibus felis. Aenean leo enim, convallis a aliquam facilisis, hendrerit vel tellus. Aenean sodales velit eget lorem aliquet dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut aliquam tincidunt semper. Sed sagittis odio ac facilisis bibendum. Quisque porttitor sit amet augue id dictum. Nam eleifend purus nisl, ultricies efficitur sem volutpat quis. Nunc cursus leo eget velit tincidunt, nec lacinia ex condimentum. Nulla commodo lectus ligula, ut sollicitudin leo laoreet at. Praesent aliquam ultricies mauris vel ultricies. Proin ligula orci, tincidunt vitae urna in, dictum luctus orci. Vestibulum vitae lacinia metus.
                Praesent viverra mauris fringilla metus ornare mattis. Sed quis sapien eget ante faucibus feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed dictum, lorem sed luctus cursus, libero enim suscipit quam, et pellentesque diam risus nec arcu. Duis quis dapibus urna. Nunc risus dolor, vulputate eu auctor aliquam, maximus non arcu. Etiam varius consectetur hendrerit. Vivamus nisl massa, mollis a ultrices congue, sollicitudin a elit. Aliquam consectetur a ipsum a gravida. Nam vel convallis nunc. Vivamus imperdiet id turpis id volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc ullamcorper tellus id nisl feugiat euismod.  */}
            </div>
        </div>
    );
}